language: node_js
node_js:
  - "12"
  - "14"
  - "node"
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'USE `test`; CREATE TABLE IF NOT EXISTS `test` (`id` int(11) NOT NULL AUTO_INCREMENT,  primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;'
