sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - iojs
before_script:
  - mysql -e 'create database test;'
  - mysql -e 'USE `test`; CREATE TABLE IF NOT EXISTS `test` (`id` int(11) NOT NULL AUTO_INCREMENT,  primary key (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;'