language: node_js
node_js:
  - "0.10"
before_script:
  - mysql -e 'create database hapi-plugin-mysql;'
  - mysql -e 'CREATE TABLE IF NOT EXISTS `test` (`id` int(11) NOT NULL AUTO_INCREMENT) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;'